CREATE TABLE AbsNote (
	id INTEGER SERIAL PRIMARY KEY,
	name TEXT NOT NULL
) WITH (
OIDS=FALSE
);

CREATE TABLE RelNote (
	id INTEGER SERIAL PRIMARY KEY
	name TEXT NOT NULL
) WITH (
OIDS=FALSE
);

CREATE TABLE Chord (
	id INTEGER SERIAL PRIMARY KEY,
	cp_id INTEGER REFERENCES ChordPattern(id) NOT NULL,
	root_an_id INTEGER REFERENCE AbsNote(id) NOT NULL
) WITH (
OIDS=FALSE
);

CREATE TABLE Scale (
	id INTEGER SERIAL PRIMARY KEY,
	sp_id INTEGER REFERENCES ScalePattern(id) NOT NULL,
	root_an_id INTEGER REFERENCE AbsNote(id) NOT NULL
) WITH (
OIDS=FALSE
);

CREATE TABLE ChordPattern (
	id INTEGER SERIAL PRIMARY KEY,
	name TEXT NOT NULL
) WITH (
OIDS=FALSE
);

CREATE TABLE ScalePattern (
	id INTEGER SERIAL PRIMARY KEY,
	name TEXT NOT NULL
) WITH (
OIDS=FALSE
);

CREATE TABLE ChordNote (
	an_id INTEGER REFERENCE AbsNote(id) NOT NULL,
	rn_id INTEGER REFERENCE RelNote(id) NOT NULL,
	c_id INTEGER REFERENCE Chord(id) NOT NULL
)
) WITH (
OIDS=FALSE
);

CREATE TABLE ScaleNote (
	an_id INTEGER REFERENCE AbsNote(id) NOT NULL,
	rn_id INTEGER REFERENCE RelNote(id) NOT NULL,
	s_id INTEGER REFERENCE Scale(id) NOT NULL
) WITH (
OIDS=FALSE
);

CREATE TABLE ChordPatternNote (
	cp_id INTEGER REFERENCE ChordPattern(id) NOT NULL,
	rn_id INTEGER REFERENCE RelNote(id) NOT NULL,
) WITH (
OIDS=FALSE
);

CREATE TABLE ScalePatternNote (
	sp_id INTEGER REFERENCE ScalePattern(id) NOT NULL,
	rn_id INTEGER REFERENCE RelNote(id) NOT NULL,
) WITH (
OIDS=FALSE
);
